version: 2
jobs:
    build:
        docker:
            - image: shiguredo/erlang:erlang-20.0.1-ubuntu-16.04
        working_directory: ~/shiguredo
        steps:
            - checkout
            - run: make

